version: '3.8'

services:
  aa_db:
    build: ./database
    container_name: aa_db
    ports:
      - "3306:3306"
      - "2222:22"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: AstroAllies_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - aa_db_data:/var/lib/mysql
    networks:
      - aa_network

  aa_app:
    build: ./webserver
    container_name: aa_app
    ports:
      - "8080:80"
      - "8443:443"
      - "2223:22"
    volumes:
      - ./webserver/AstroAllies:/var/www/html
    depends_on:
      - aa_db
    networks:
      - aa_network

volumes:
  aa_db_data:

networks:
  aa_network:
    driver: bridge
