FROM mariadb:10.5

RUN apt-get update && apt-get install -y openssh-server \
 && echo 'root:rootpsw' | chpasswd \
 && mkdir /var/run/sshd \
 && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

EXPOSE 22

CMD service ssh start && docker-entrypoint.sh mysqld
